linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic

jobs:
  include:
    - stage: vulkan_lunarg_installer
      <<: *linux
      env: BUILD_VULKAN_LUNARG_INSTALLER=1 CONAN_DOCKER_IMAGE=conanio/gcc8 ARCH=x86_64
    - <<: *osx
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 BUILD_VULKAN_LUNARG_INSTALLER=1 ARCH=x86_64
    - stage: vulkan_lunarg
      <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 ARCH=x86_64
    - <<: *osx
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 ARCH=x86_64

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
