linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic

jobs:
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_ARCHS=x86_64 ARCH=x86_64 CONAN_BUILD_TYPES=Release CPT_TEST_FOLDER=test_package_installer CONAN_CONANFILE=conanfile_installer.py
    - <<: *osx
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_ARCHS=x86_64 ARCH=x86_64 CONAN_BUILD_TYPES=Release CPT_TEST_FOLDER=test_package_installer CONAN_CONANFILE=conanfile_installer.py
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_ARCHS=x86_64 ARCH=x86_64 CONAN_BUILD_TYPES=Release
    - <<: *osx
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_ARCHS=x86_64 ARCH=x86_64 CONAN_BUILD_TYPES=Release

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
