build: off

environment:
  PYTHON: "C:\\Python37-x64"

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Release
      CONAN_VISUAL_RUNTIMES: MT
      ARCH: x86
      CONAN_ARCHS: x86
      CPT_TEST_FOLDER: test_package_installer
      CONAN_CONANFILE: conanfile_installer.py
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Release
      CONAN_VISUAL_RUNTIMES: MT
      ARCH: x86_64
      CONAN_ARCHS: x86_64
      CPT_TEST_FOLDER: test_package_installer
      CONAN_CONANFILE: conanfile_installer.py
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Release
      CONAN_VISUAL_RUNTIMES: MT
      ARCH: x86
      CONAN_ARCHS: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Release
      CONAN_VISUAL_RUNTIMES: MT
      ARCH: x86_64
      CONAN_ARCHS: x86_64

install:
  - set PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
