build: off

environment:
  PYTHON: "C:\\Python37-x64"

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BUILD_VULKAN_LUNARG_INSTALLER: 1
      ARCH: x86,x86_64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BUILD_VULKAN_LUNARG_INSTALLER: 0
      ARCH: x86,x86_64

install:
  - set PATH=%PYTHON%/Scripts;%PYTHON%;%PATH%
  - python -m pip install --upgrade conan conan-package-tools
  - conan user

test_script:
  - python build.py
